Repository Tsunghao-C/ft_Transcendence, pull requests merged in 2024-12, with the labels that each got.

#30 Front to back connection
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/404.js
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/data_test.js
  pong-game/frontend/nginx/spa_files/javascript/fetch_request.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/game_menu.js
  pong-game/frontend/nginx/spa_files/javascript/home.js
  pong-game/frontend/nginx/spa_files/javascript/language_pack.js
  pong-game/frontend/nginx/spa_files/javascript/leaderboard.js
  pong-game/frontend/nginx/spa_files/javascript/login.js
  pong-game/frontend/nginx/spa_files/javascript/login_html.js
  pong-game/frontend/nginx/spa_files/javascript/login_login.js
  pong-game/frontend/nginx/spa_files/javascript/login_register.js
  pong-game/frontend/nginx/spa_files/javascript/login_validations.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/personnal-data.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
  pong-game/frontend/nginx/spa_files/javascript/settings.js
  pong-game/game-service/app/user_service/models.py
  pong-game/game-service/app/user_service/urls.py
  pong-game/game-service/app/user_service/views.py
Labels: Ready to Merge

#41 Mono backend test chat ws
  pong-game/.env.example
  pong-game/docker-compose.yml
  pong-game/frontend/nginx/nginx.conf
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/game-service/Dockerfile
  pong-game/game-service/app/backend/asgi.py
  pong-game/game-service/app/backend/settings.py
  pong-game/game-service/app/chat/consumers.py
  pong-game/game-service/app/chat/routing.py
  pong-game/game-service/app/chat/templates/chat/chatroom.html
  pong-game/game-service/app/chat/templates/chat/index.html
  pong-game/game-service/app/chat/templates/chat/lobby.html
  pong-game/game-service/app/chat/urls.py
  pong-game/game-service/app/chat/views.py
  pong-game/game-service/entrypoint.sh
  pong-game/game-service/requirements.txt
Labels: ready for review

#42 fetch improve and some request fixing
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/fetch_request.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/home.js
  pong-game/frontend/nginx/spa_files/javascript/language_pack.js
  pong-game/frontend/nginx/spa_files/javascript/login_html.js
  pong-game/frontend/nginx/spa_files/javascript/login_register.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/personnal-data.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
  pong-game/game-service/app/user_service/views.py
Labels: ready for review

#44 Game ws bringup
  pong-game/docker-compose.yml
  pong-game/frontend/nginx/nginx.conf
  pong-game/game-service/app/backend/asgi.py
  pong-game/game-service/app/backend/settings.py
  pong-game/game-service/app/backend/urls.py
  pong-game/game-service/app/chat/consumers.py
  pong-game/game-service/app/game_service/consumers.py
  pong-game/game-service/app/game_service/routing.py
  pong-game/game-service/app/game_service/templates/game_service/game_test.html
  pong-game/game-service/app/game_service/urls.py
  pong-game/game-service/app/game_service/views.py
  pong-game/game-service/requirements.txt
Labels: ready for review

#55 adding pagination to leaderboard and searchbar
  pong-game/backend/app/game_service/views.py
  pong-game/frontend/nginx/spa_files/javascript/leaderboard.js
Labels: ready for review

#62 Setting back 2FA + more cosmetics
  pong-game/.env.example
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/media/default.jpg
  pong-game/backend/app/test/req_02_validate.sh
  pong-game/backend/app/user_service/models.py
  pong-game/backend/app/user_service/urls.py
  pong-game/backend/app/user_service/views.py
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat_old.js
  pong-game/frontend/nginx/spa_files/javascript/language_pack.js
  pong-game/frontend/nginx/spa_files/javascript/login_html.js
  pong-game/frontend/nginx/spa_files/javascript/login_login.js
  pong-game/frontend/nginx/spa_files/javascript/login_register.js
  pong-game/frontend/nginx/spa_files/javascript/login_validations.js
  pong-game/frontend/nginx/spa_files/javascript/personal-data.js
  pong-game/frontend/nginx/spa_files/javascript/settings.js
  pong-game/frontend/nginx/spa_files/styles.css
Labels: ready for review

#58 WS healthcheck automation
  .github/workflows/ci.yml
  .gitignore
  Makefile
  README.md
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/chat/consumers.py
  pong-game/backend/app/chat/routing.py
  pong-game/backend/app/chat/templates/chat/chat_test.html
  pong-game/backend/app/chat/urls.py
  pong-game/backend/app/chat/views.py
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/routing.py
  pong-game/backend/app/game_service/templates/game_service/game_test.html
  pong-game/backend/app/game_service/templates/game_service/game_test_ssr.html
  pong-game/backend/app/game_service/urls.py
  pong-game/backend/app/game_service/views.py
  pong-game/docker-compose.yml
  pong-game/frontend/nginx/nginx.conf
  pong-game/tests/prepare_libs.sh
  pong-game/tests/websocket_check.sh
  pong-game/tests/websockets-10.4.whl
Labels: ready for review

#65 Chat features
  pong-game/backend/app/backend/asgi.py
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/chat/apps.py
  pong-game/backend/app/chat/consumers.py
  pong-game/backend/app/chat/migrations/__init__.py
  pong-game/backend/app/chat/migrations/__pycache__/__init__.cpython-311.pyc
  pong-game/backend/app/chat/models.py
  pong-game/backend/app/chat/routing.py
  pong-game/backend/app/chat/serializers.py
  pong-game/backend/app/chat/urls.py
  pong-game/backend/app/chat/views.py
  pong-game/backend/app/user_service/models.py
  pong-game/backend/entrypoint.sh
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/frontend/nginx/spa_files/javascript/data_test.js
  pong-game/frontend/nginx/spa_files/javascript/fetch_request.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/login_login.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/personal-data.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
  pong-game/frontend/nginx/spa_files/javascript/settings.js
Labels: ready for review

#66 Game menu
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/gameDraw.js
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/game_menu.js
  pong-game/frontend/nginx/spa_files/javascript/game_solo.js
  pong-game/frontend/nginx/spa_files/javascript/game_test.js
  pong-game/frontend/nginx/spa_files/javascript/joinMatch.js
  pong-game/frontend/nginx/spa_files/javascript/leaderboard.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/personal-data.js
  pong-game/frontend/nginx/spa_files/javascript/privateMatch.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
Labels: ready for review

#75 Game lobby
  pong-game/backend/app/chat/models.py
  pong-game/backend/app/chat/serializers.py
  pong-game/backend/app/chat/urls.py
  pong-game/backend/app/chat/views.py
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/game_room.py
  pong-game/backend/app/game_service/templates/game_service/game.html
  pong-game/backend/app/game_service/templates/game_service/solo_game.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/frontend/nginx/spa_files/javascript/fetch_request.js
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
Labels: Ready to Merge, ready for review

#90 ELK internal TLS patch
  pong-game/.env.example
  pong-game/docker-compose.yml
  pong-game/monitoring/elk/create-certs.sh
  pong-game/monitoring/elk/elasticsearch/setup/cluster.sh
  pong-game/monitoring/elk/elasticsearch/setup/init.sh
  pong-game/monitoring/elk/elasticsearch/setup/templates.sh
  pong-game/monitoring/elk/filebeat/filebeat.yml
  pong-game/monitoring/elk/kibana/setup/import-dashboards.sh
  pong-game/monitoring/elk/logstash/config/logstash.yml
  pong-game/monitoring/elk/logstash/docker-entrypoint.sh
  pong-game/monitoring/elk/logstash/pipeline/logstash.conf
Labels: ready for review

#89 Game modes into front end
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/game_room.py
  pong-game/backend/app/game_service/models.py
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/game_menu.js
  pong-game/frontend/nginx/spa_files/javascript/game_solo.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
  pong-game/frontend/nginx/spa_files/javascript/utils.js
  pong-game/frontend/nginx/spa_files/styles.css
Labels: ready for review

#97 Update Ux and Display in Game section 00
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/game_menu.js
  pong-game/frontend/nginx/spa_files/javascript/game_solo.js
  pong-game/frontend/nginx/spa_files/javascript/game_utils.js
  pong-game/frontend/nginx/spa_files/javascript/home.js
  pong-game/frontend/nginx/spa_files/javascript/language_pack.js
  pong-game/frontend/nginx/spa_files/styles.css
Labels: Ready to Merge

#108 Vault integrate and implemented on Django
  .gitignore
  Makefile
  pong-game/.env.example
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/vault_helper.py
  pong-game/backend/entrypoint.sh
  pong-game/backend/requirements.txt
  pong-game/docker-compose.yml
  pong-game/security/vault/Dockerfile
  pong-game/security/vault/init.sh
  pong-game/security/vault/vault.hcl
  pong-game/security/vault_debian/init.sh
  pong-game/security/vault_debian/tests/get_secret.sh
  pong-game/security/vault_debian/tests/post_secret.sh
  pong-game/tests/websocket_check.sh
Labels: ready for review
