Repository Tsunghao-C/ft_Transcendence, pull requests merged in 2025-01, with the labels that each got.

#107 Creates log files for gameRooms and gameConsumers, updates respective loggers.
  README.md
  image/monolithic_diagram4.png
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/game_room.py
  pong-game/backend/entrypoint.sh
  pong-game/docker-compose.yml
  pong-game/monitoring/elk/elasticsearch/setup/templates.sh
  pong-game/monitoring/elk/filebeat/filebeat.yml
  pong-game/monitoring/elk/kibana/dashboards/django/django_game_logs.ndjson
  pong-game/monitoring/elk/logstash/pipeline/logstash.conf
Labels: ready for review

#116 Clean testendpoints and unused files
  Makefile
  pong-game/backend/app/chat/consumers.py
  pong-game/backend/app/chat/templates/chat/chatroom.html
  pong-game/backend/app/chat/templates/chat/index.html
  pong-game/backend/app/chat/urls.py
  pong-game/backend/app/chat/views.py
  pong-game/backend/app/game_service/templates/game_service/game.html
  pong-game/backend/app/game_service/templates/game_service/game_test_ssr.html
  pong-game/backend/app/game_service/templates/game_service/solo_game.html
  pong-game/backend/app/game_service/urls.py
  pong-game/backend/app/game_service/views.py
  pong-game/backend/app/test/req_01_login.sh
  pong-game/backend/app/test/req_02_validate.sh
  pong-game/backend/app/user_service/templates/user_service/change_password.html
  pong-game/backend/app/user_service/templates/user_service/login.html
  pong-game/backend/app/user_service/templates/user_service/password_change.html
  pong-game/backend/app/user_service/templates/user_service/password_change_done.html
  pong-game/backend/app/user_service/urls.py
  pong-game/docker-compose.yml
  pong-game/frontend/nginx/nginx.conf
  pong-game/frontend/spa/Dockerfile
  pong-game/frontend/spa/package.json
  pong-game/security/2fa/Dockerfile
  pong-game/security/2fa/requirements.txt
  pong-game/security/2fa/src/__init__.py
  pong-game/security/2fa/src/app.py
  pong-game/security/waf/Dockerfile
  pong-game/security/waf/nginx/default.conf
  pong-game/security/waf/nginx/nginx.conf
  pong-game/security/waf/rules/custom.conf
Labels: ready for review

#106 Adds basic front support for rejoining an ongoing game
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/game_room.py
  pong-game/frontend/nginx/spa_files/javascript/game_utils.js
  pong-game/frontend/nginx/spa_files/styles.css
Labels: Ready to Merge

#119 Cleaning and translation
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/user_service/models.py
  pong-game/backend/app/user_service/serializers.py
  pong-game/frontend/nginx/spa_files/index.html
  pong-game/frontend/nginx/spa_files/javascript/about.js
  pong-game/frontend/nginx/spa_files/javascript/app.js
  pong-game/frontend/nginx/spa_files/javascript/chat_view.js
  pong-game/frontend/nginx/spa_files/javascript/friends.js
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/game_local.js
  pong-game/frontend/nginx/spa_files/javascript/game_menu.js
  pong-game/frontend/nginx/spa_files/javascript/game_solo.js
  pong-game/frontend/nginx/spa_files/javascript/game_tournament.js
  pong-game/frontend/nginx/spa_files/javascript/game_utils.js
  pong-game/frontend/nginx/spa_files/javascript/home.js
  pong-game/frontend/nginx/spa_files/javascript/language_pack.js
  pong-game/frontend/nginx/spa_files/javascript/leaderboard.js
  pong-game/frontend/nginx/spa_files/javascript/login_html.js
  pong-game/frontend/nginx/spa_files/javascript/login_login.js
  pong-game/frontend/nginx/spa_files/javascript/login_register.js
  pong-game/frontend/nginx/spa_files/javascript/manage_social.js
  pong-game/frontend/nginx/spa_files/javascript/personal-data.js
  pong-game/frontend/nginx/spa_files/javascript/profile.js
Labels: Good PR

#125 Promethus and grafana is up
  pong-game/.env.example
  pong-game/backend/app/backend/settings.py
  pong-game/backend/app/backend/urls.py
  pong-game/backend/app/user_service/middleware.py
  pong-game/backend/requirements.txt
  pong-game/docker-compose.yml
  pong-game/monitoring/grafana/Dockerfile
  pong-game/monitoring/grafana/grafana.ini
  pong-game/monitoring/grafana/provisioning/dashboards/dashboard.yml
  pong-game/monitoring/grafana/provisioning/dashboards/django_metrics/django_metrics.json
  pong-game/monitoring/grafana/provisioning/dashboards/node_exporter_full/node_exporter_full.json
  pong-game/monitoring/grafana/provisioning/datasources/datasource.yml
  pong-game/monitoring/node_exporter/Dockerfile
  pong-game/monitoring/prometheus/Dockerfile
  pong-game/monitoring/prometheus/alert.rules
  pong-game/monitoring/prometheus/conf/alert.rules
  pong-game/monitoring/prometheus/conf/prometheus.yml
  pong-game/monitoring/prometheus/conf/web-config.yml
  pong-game/monitoring/prometheus/prometheus.yml
  pong-game/security/vault/init.sh
Labels: ready for review

#122 Fixed ready-button not being hidden anymorein games anymore.
  pong-game/backend/app/game_service/consumers.py
  pong-game/backend/app/game_service/game_room.py
  pong-game/frontend/nginx/spa_files/javascript/game_lobby.js
  pong-game/frontend/nginx/spa_files/javascript/game_local.js
  pong-game/frontend/nginx/spa_files/javascript/game_solo.js
  pong-game/frontend/nginx/spa_files/javascript/game_utils.js
  pong-game/frontend/nginx/spa_files/javascript/utils.js
Labels: Ready to Merge, Good PR

#135 Prometheus Grafana TLS FIX
  .gitignore
  Makefile
  docker-compose.yml
  pong-game/monitoring/create-monitoring-certs.sh
  pong-game/monitoring/grafana/Dockerfile
  pong-game/monitoring/grafana/grafana.ini
  pong-game/monitoring/grafana/prepare-datasource.sh
  pong-game/monitoring/grafana/provisioning/datasources/datasource.yml
  pong-game/monitoring/prometheus/Dockerfile
  pong-game/monitoring/prometheus/conf/prometheus.yml
Labels: ready for review
